#!/bin/bash -l

export PATH=/usr/local/bin:$PATH

NUBIS_PROJECT=$(nubis-metadata NUBIS_PROJECT)
NUBIS_ENVIRONMENT=$(nubis-metadata NUBIS_ENVIRONMENT)

LOCK="${NUBIS_PROJECT}-${NUBIS_ENVIRONMENT}-backup"

# Redirect logs to a log file
exec &> >(tee >( ts >> "/var/log/${NUBIS_PROJECT}-backup.log")) 2>&1

CONFIGS="/etc/vertica-backup*.conf"
USERNAME=dbadmin
VBR=/opt/vertica/bin/vbr

function init () {
  echo "Initializing Backups"
  INIT_RV=0
  for CONFIG in $CONFIGS; do
    echo "[$CONFIG]"
    su - $USERNAME -c "$VBR --task init --s3-force-init -c $CONFIG --debug 3"
    RV=$?
    INIT_RV=$(( INIT_RV || RV ))
  done
  return $INIT_RV
}

function backup () {
  echo "Performing Backup"
  BACKUP_RV=0

  for CONFIG in $CONFIGS; do
    echo "[$CONFIG]"
    su - $USERNAME -c "$VBR --task backup -c $CONFIG --debug 3"
    RV=$?
    BACKUP_RV=$(( BACKUP_RV || RV ))
    su - $USERNAME -c "$VBR --task listbackup -c $CONFIG --debug 3"
  done

  return $BACKUP_RV
}

# Are we the current backup leader ?
if consul-do "${LOCK}" "$(hostname)"; then
  echo "We are the backup leader"
  
  ACTION=$1

  case $ACTION in
    backup)
      init
      backup
      exit $?
      ;;
    init)
      init
      exit $?
      ;;
    *)
      echo "Usage: $0 [backup|init]"
      exit 1
      ;;
  esac
else
  echo "We are not the current backup leader, noop"
  exit
fi
